version: 2
jobs:
  build:
    docker:
      - image: php:7
      - image: mysql:5
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
      - image: selenium/standalone-chrome:3
    working_directory: ~/your-repository-name
    steps:
      - checkout

      # Update Composer and install dependencies
      - run: composer self-update
      - run: composer install --prefer-dist

      # Setup database
      - run: php app/console doctrine:database:create --env=test
      - run: php app/console doctrine:schema:create --env=test

      - run:
          name: Run web server
          command: php app/console server:run --env=test -vvv localhost:8080 > server.log 2>&1
          background: true

      # Run tests
      - run: php vendor/bin/behat
      # and maybe some unit tests

      # Run tests
      - run: mkdir var/behat_screenshots/
      # add an empty file so that the directory isn't empty (else copy may fail)
      - run: touch var/behat_screenshots/empty.txt

      - run:
          name: Run Behat tests
          command: php vendor/bin/behat
          # Export environment variable for this single command shell
          environment:
            BEHAT_SCREENSHOTS: '1'
      # and maybe some unit tests

      - store_artifacts:
          path: var/behat_screenshots/