version: 2
jobs:
  build:
    docker:
      - image: php:7
      - image: mysql:5
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
      - image: selenium/standalone-chrome:3
    working_directory: ~/your-repository-name
    steps:
      - checkout

      # Update Composer and install dependencies
      - run: composer self-update
      - run: composer install --prefer-dist

      # Setup database
      - run: php bin/console doctrine:database:create --env=test
      - run: php bin/console doctrine:schema:create --env=test

      - run:
          name: Run web server
          command: php bin/console server:run --env=test -vvv localhost:8080 > server.log 2>&1
          background: true

      # Run tests
      - run: ./vendor/bin/behat
